version: '3.9'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    restart: always
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../CarWorkshop/backend/:/usr/src/CarWorkshop/
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db
    restart: always
  workshop:
    build: ./workshop
    environment: 
      PORT: 4200
    command: "ng serve --host 0.0.0.0 --poll=2000 --port 4200 --disable-host-check --hmr"
    volumes:
      - ./workshop/my-app/:/workshop/
      - /workshop/node_modules
    ports:
      - "80:4200"
  warehouse:
    build: ./warehouse
    environment: 
      PORT: 3000
    command: "npm start"
    volumes:
      - ./warehouse/my-app/:/warehouse/
      - /warehouse/node_modules
    ports:
      - "3000:3000"
volumes:
  postgres_data: